#!/usr/bin/env python3

import os
import subprocess
import sys

script = sys.argv[1]
script_folder = os.path.dirname(script)
script_name = os.path.basename(script)

# Move cwd to the script location, poetry will look in the same folder and its parents for the pyproject.toml file
proc = subprocess.Popen(["poetry", "run", "python", script_name] + sys.argv[2:], cwd=script_folder)
sys.exit(proc.wait())
