#!/usr/bin/env python3

import os
import subprocess
import sys


def get_pyproject(dir):
    dir = os.path.dirname(dir)
    if dir == "/":
        return ""
    pyproject = dir + "/pyproject.toml"
    if os.path.exists(pyproject):
        return pyproject
    else:
        return get_pyproject(dir)


script = sys.argv[1]
pyproject = get_pyproject(os.path.realpath(script))

if pyproject:
    env = os.environ.copy()
    env["POETRY_PYPROJECT"] = pyproject
    proc = subprocess.Popen(["poetry", "run", "python", script] + sys.argv[2:], env=env)
    sys.exit(proc.wait())
else:
    print("Could not locate the pyproject file for $SCRIPT.")
    sys.exit(1)
